import { getDisplayPartNumber } from '../display-utils';
import { MinimalItem, COST_CATEGORIES, resolveCostCategory, isCleatItem } from './categorization';

// ---------------------------------------------------------
// WORKSHOP ACTIVITY LABELS
// ---------------------------------------------------------
export const WORKSHOP_ACTIVITIES = {
    FRAME_ASSEMBLING: 'Frame Assembling',
    SWITCHGEAR_MOUNTING: 'Switchgear & Component Mounting',
    BUSBAR_ASSEMBLING: 'Busbar Assembling',
    WIRING: 'Wiring',
    FIXING_LABELS: 'Fixing Labels',
    INSPECTION_TESTING: 'Inspection & Testing',
    PACKAGING_FREIGHT: 'Packaging & Freight',
    ONSITE_WORKS: 'Onsite Works',
    OTHER: 'Other'
} as const;

// ---------------------------------------------------------
// EXPLICIT PART NUMBER REGISTRIES
// ---------------------------------------------------------
const EXPLICIT_PART_MAP: Record<string, string> = {
    // 04 - Frame Assembling
    'IFM-50KA': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFM-COLOUR': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFM-COMPARTMENTS': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFM-TIERS': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-600MM': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-800MM': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-ABLOY': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-BASE': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-COMPARTMENTS': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-DOORS': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-DUAL-LOCK': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-QUOTED': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-SS-2B': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-SS-NO4': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'IFC-TIERS-400': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'MISC-CABLE-TRAY': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,
    'MISC-HARDWARE': WORKSHOP_ACTIVITIES.FRAME_ASSEMBLING,

    // 05 - Switchgear & Component Mounting
    'CT-COMPARTMENTS': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-CTC400': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-PANEL': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-S-TYPE': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-T-TYPE': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-TEST-BLOCK': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-U-TYPE': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    'CT-W-TYPE': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-CHASSIS-18': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-CHASSIS-24': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-CHASSIS-30': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-FUSE': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-MCB-1PH': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-MCB-3PH': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-NEUTRAL-LINK': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,
    '100A-PANEL': WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING,

    // 06 - Busbar Assembling
    'IFC1-CLEAT-LARGE-2': WORKSHOP_ACTIVITIES.BUSBAR_ASSEMBLING,
    'IFC1-CLEAT-LARGE-3': WORKSHOP_ACTIVITIES.BUSBAR_ASSEMBLING,
    'IFC1-CLEAT-SMALL-1': WORKSHOP_ACTIVITIES.BUSBAR_ASSEMBLING,
    'IFC1-CLEAT-SMALL-2': WORKSHOP_ACTIVITIES.BUSBAR_ASSEMBLING,

    // 07 - Wiring
    'CT-WIRING': WORKSHOP_ACTIVITIES.WIRING,
    '100A-WIRING-1PH': WORKSHOP_ACTIVITIES.WIRING,
    '100A-WIRING-3PH': WORKSHOP_ACTIVITIES.WIRING,
    'IPD-WIRING-DIGITAL': WORKSHOP_ACTIVITIES.WIRING,
    'IPD-WIRING-SURGE': WORKSHOP_ACTIVITIES.WIRING,
    'CHD-WIRING-CONTROL': WORKSHOP_ACTIVITIES.WIRING,
    'MTZ_ACB_LOGIC': WORKSHOP_ACTIVITIES.WIRING,
    'SCH_ATS_LOGIC': WORKSHOP_ACTIVITIES.WIRING,

    // 08 - Fixing Labels
    'MISC-LABELS': WORKSHOP_ACTIVITIES.FIXING_LABELS,

    // 09 - Inspection & Testing
    'MISC-TEST-TIERS': WORKSHOP_ACTIVITIES.INSPECTION_TESTING,

    // 10 - Packaging & Freight
    'MISC-DELIVERY-HIAB': WORKSHOP_ACTIVITIES.PACKAGING_FREIGHT,
    'MISC-DELIVERY-UTE': WORKSHOP_ACTIVITIES.PACKAGING_FREIGHT,

    // 11 - Onsite Works
    'MISC-SITE-RECONNECTION': WORKSHOP_ACTIVITIES.ONSITE_WORKS,
};

// ---------------------------------------------------------
// DETERMINISTIC RESOLVER (No Fallbacks)
// ---------------------------------------------------------
export function resolveWorkshopActivity(item: MinimalItem): string {
    const rawPartNumber = (item.partNumber || item.name || '').trim().toUpperCase();
    const partNumber = getDisplayPartNumber(rawPartNumber);

    // 1. Check explicit part number mappings first
    if (EXPLICIT_PART_MAP[partNumber]) {
        return EXPLICIT_PART_MAP[partNumber];
    }

    // 2. Busbar Assembling (If the resolved cost category is Busbars/Insulation, or is a cleat)
    const costCategory = resolveCostCategory(item);
    if (
        costCategory === COST_CATEGORIES.BUSBARS || 
        costCategory === COST_CATEGORIES.BUSBAR_INSULATION ||
        isCleatItem(item)
    ) {
        return WORKSHOP_ACTIVITIES.BUSBAR_ASSEMBLING;
    }

    // 3. Switchgear & Component Mounting
    // Matches Circuit Breakers, Isolators, CT Metering, or Miscellaneous categories
    // (Notice that wiring parts like CT-WIRING, etc., have already been matched in Step 1)
    if (
        costCategory === COST_CATEGORIES.CIRCUIT_BREAKERS ||
        costCategory === COST_CATEGORIES.ISOLATORS ||
        costCategory === COST_CATEGORIES.CT_METERING ||
        costCategory === COST_CATEGORIES.MISCELLANEOUS
    ) {
        return WORKSHOP_ACTIVITIES.SWITCHGEAR_MOUNTING;
    }

    // 4. Default fallback: Unclassified items -> "Other"
    return WORKSHOP_ACTIVITIES.OTHER;
}
