export type RowDef = 
  | { type: 'single'; partNumber: string }
  | { type: 'paired'; tripPartNumber: string; basePartNumber: string }
  | { type: 'sideBySide'; partNumberA: string; partNumberB: string };

export type SectionDef = {
    heading: string;
    rows: RowDef[];
};

export const SG_CBS_LAYOUT: SectionDef[] = [
    {
        heading: "Circuit Breakers – 1P 25/40 kA",
        rows: [
            { type: 'single', partNumber: 'C10N1TM063' },
            { type: 'single', partNumber: 'C10N1TM080' },
            { type: 'single', partNumber: 'C10M1TM063' },
            { type: 'single', partNumber: 'C10M1TM100' }
        ]
    },
    {
        heading: "Circuit Breakers – 3P 25kA",
        rows: [
            { type: 'single', partNumber: 'C10B3TM063' },
            { type: 'single', partNumber: 'C10B3TM100' },
            { type: 'single', partNumber: 'C10B32D100' },
            { type: 'paired', tripPartNumber: 'C1035E100', basePartNumber: 'C10B3' },
            { type: 'paired', tripPartNumber: 'C1036E100', basePartNumber: 'C10B3' },
            { type: 'single', partNumber: 'C16B3TM100' },
            { type: 'single', partNumber: 'C16B3TM125' },
            { type: 'single', partNumber: 'C16B3TM160' },
            { type: 'single', partNumber: 'C16B32D160' },
            { type: 'paired', tripPartNumber: 'C1635E160', basePartNumber: 'C16B3' },
            { type: 'paired', tripPartNumber: 'C1636E160', basePartNumber: 'C16B3' },
            { type: 'single', partNumber: 'C25B3TM125' },
            { type: 'single', partNumber: 'C25B3TM160' },
            { type: 'single', partNumber: 'C25B3TM200' },
            { type: 'single', partNumber: 'C25B3TM250' },
            { type: 'single', partNumber: 'C25B32D250' },
            { type: 'paired', tripPartNumber: 'C2535E250', basePartNumber: 'C25B3' },
            { type: 'paired', tripPartNumber: 'C2536E250', basePartNumber: 'C25B3' }
        ]
    },
    {
        heading: "Circuit Breakers – 3P 36kA",
        rows: [
            { type: 'single', partNumber: 'C10F3TM063' },
            { type: 'single', partNumber: 'C10F3TM100' },
            { type: 'single', partNumber: 'C10F32D100' },
            { type: 'paired', tripPartNumber: 'C1035E100', basePartNumber: 'C10F3' },
            { type: 'paired', tripPartNumber: 'C1036E100', basePartNumber: 'C10F3' },
            { type: 'single', partNumber: 'C16F3TM100' },
            { type: 'single', partNumber: 'C16F3TM125' },
            { type: 'single', partNumber: 'C16F3TM160' },
            { type: 'single', partNumber: 'C16F32D160' },
            { type: 'paired', tripPartNumber: 'C1635E160', basePartNumber: 'C16F3' },
            { type: 'paired', tripPartNumber: 'C1636E160', basePartNumber: 'C16F3' },
            { type: 'single', partNumber: 'C25F3TM125' },
            { type: 'single', partNumber: 'C25F3TM160' },
            { type: 'single', partNumber: 'C25F3TM200' },
            { type: 'single', partNumber: 'C25F3TM250' },
            { type: 'single', partNumber: 'C25F32D250' },
            { type: 'paired', tripPartNumber: 'C2535E250', basePartNumber: 'C25F3' },
            { type: 'paired', tripPartNumber: 'C2536E250', basePartNumber: 'C25F3' },
            { type: 'single', partNumber: 'C40F32D400' },
            { type: 'paired', tripPartNumber: 'C4035E400', basePartNumber: 'C40F3' },
            { type: 'paired', tripPartNumber: 'C4036E400', basePartNumber: 'C40F3' },
            { type: 'single', partNumber: 'C63F32D630' },
            { type: 'paired', tripPartNumber: 'C6335E630', basePartNumber: 'C63F3' },
            { type: 'paired', tripPartNumber: 'C6336E630', basePartNumber: 'C63F3' }
        ]
    },
    {
        heading: "Circuit Breakers – 3P 50kA",
        rows: [
            { type: 'single', partNumber: 'C10N3TM063' },
            { type: 'single', partNumber: 'C10N3TM100' },
            { type: 'single', partNumber: 'C10N32D100' },
            { type: 'paired', tripPartNumber: 'C1035E100', basePartNumber: 'C10N3' },
            { type: 'paired', tripPartNumber: 'C1036E100', basePartNumber: 'C10N3' },
            { type: 'single', partNumber: 'C16N3TM100' },
            { type: 'single', partNumber: 'C16N3TM125' },
            { type: 'single', partNumber: 'C16N3TM160' },
            { type: 'single', partNumber: 'C16N32D160' },
            { type: 'paired', tripPartNumber: 'C1635E160', basePartNumber: 'C16N3' },
            { type: 'paired', tripPartNumber: 'C1636E160', basePartNumber: 'C16N3' },
            { type: 'single', partNumber: 'C25N3TM125' },
            { type: 'single', partNumber: 'C25N3TM160' },
            { type: 'single', partNumber: 'C25N3TM200' },
            { type: 'single', partNumber: 'C25N3TM250' },
            { type: 'single', partNumber: 'C25N32D250' },
            { type: 'paired', tripPartNumber: 'C2535E250', basePartNumber: 'C25N3' },
            { type: 'paired', tripPartNumber: 'C2536E250', basePartNumber: 'C25N3' },
            { type: 'single', partNumber: 'C40N32D400' },
            { type: 'paired', tripPartNumber: 'C4035E400', basePartNumber: 'C40N3' },
            { type: 'paired', tripPartNumber: 'C4036E400', basePartNumber: 'C40N3' },
            { type: 'single', partNumber: 'C63N32D630' },
            { type: 'paired', tripPartNumber: 'C6335E630', basePartNumber: 'C63N3' },
            { type: 'paired', tripPartNumber: 'C6336E630', basePartNumber: 'C63N3' },
            { type: 'single', partNumber: '33460' },
            { type: 'single', partNumber: '33223' },
            { type: 'single', partNumber: '33546' },
            { type: 'single', partNumber: '33323' },
            { type: 'single', partNumber: '34420' },
            { type: 'paired', tripPartNumber: '47058', basePartNumber: '33460' },
            { type: 'paired', tripPartNumber: '47061', basePartNumber: '33460' },
            { type: 'paired', tripPartNumber: '47059', basePartNumber: '33460' },
            { type: 'paired', tripPartNumber: '47062', basePartNumber: '33460' },
            { type: 'single', partNumber: '33466' },
            { type: 'single', partNumber: '33233' },
            { type: 'single', partNumber: '33552' },
            { type: 'single', partNumber: '33333' },
            { type: 'single', partNumber: '34424' },
            { type: 'paired', tripPartNumber: '47058', basePartNumber: '33466' },
            { type: 'paired', tripPartNumber: '47061', basePartNumber: '33466' },
            { type: 'paired', tripPartNumber: '47059', basePartNumber: '33466' },
            { type: 'paired', tripPartNumber: '47062', basePartNumber: '33466' },
            { type: 'single', partNumber: '33472' },
            { type: 'single', partNumber: '33243' },
            { type: 'single', partNumber: '33558' },
            { type: 'single', partNumber: '33343' },
            { type: 'single', partNumber: '34428' },
            { type: 'paired', tripPartNumber: '47058', basePartNumber: '33472' },
            { type: 'paired', tripPartNumber: '47061', basePartNumber: '33472' },
            { type: 'paired', tripPartNumber: '47059', basePartNumber: '33472' },
            { type: 'paired', tripPartNumber: '47062', basePartNumber: '33472' },
            { type: 'single', partNumber: '33478' },
            { type: 'single', partNumber: '33253' },
            { type: 'single', partNumber: '33564' },
            { type: 'single', partNumber: '33353' },
            { type: 'single', partNumber: '34432' },
            { type: 'paired', tripPartNumber: '47058', basePartNumber: '33478' },
            { type: 'paired', tripPartNumber: '47061', basePartNumber: '33478' },
            { type: 'paired', tripPartNumber: '47059', basePartNumber: '33478' },
            { type: 'paired', tripPartNumber: '47062', basePartNumber: '33478' },
            { type: 'single', partNumber: '33482' },
            { type: 'single', partNumber: '33263' },
            { type: 'single', partNumber: '33568' },
            { type: 'single', partNumber: '33363' },
            { type: 'single', partNumber: '34436' },
            { type: 'paired', tripPartNumber: '47058', basePartNumber: '33482' },
            { type: 'paired', tripPartNumber: '47061', basePartNumber: '33482' },
            { type: 'paired', tripPartNumber: '47059', basePartNumber: '33482' },
            { type: 'paired', tripPartNumber: '47062', basePartNumber: '33482' }
        ]
    },
    {
        heading: "Circuit Breakers – 3P 70kA",
        rows: [
            { type: 'single', partNumber: 'C10H3TM063' },
            { type: 'single', partNumber: 'C10H3TM100' },
            { type: 'single', partNumber: 'C10H32D100' },
            { type: 'paired', tripPartNumber: 'C1035E100', basePartNumber: 'C10H3' },
            { type: 'paired', tripPartNumber: 'C1036E100', basePartNumber: 'C10H3' },
            { type: 'single', partNumber: 'C16H3TM100' },
            { type: 'single', partNumber: 'C16H3TM125' },
            { type: 'single', partNumber: 'C16H3TM160' },
            { type: 'single', partNumber: 'C16H32D160' },
            { type: 'paired', tripPartNumber: 'C1635E160', basePartNumber: 'C16H3' },
            { type: 'paired', tripPartNumber: 'C1636E160', basePartNumber: 'C16H3' },
            { type: 'single', partNumber: 'C25H3TM125' },
            { type: 'single', partNumber: 'C25H3TM160' },
            { type: 'single', partNumber: 'C25H3TM200' },
            { type: 'single', partNumber: 'C25H3TM250' },
            { type: 'single', partNumber: 'C25H32D250' },
            { type: 'paired', tripPartNumber: 'C2535E250', basePartNumber: 'C25H3' },
            { type: 'paired', tripPartNumber: 'C2536E250', basePartNumber: 'C25H3' },
            { type: 'single', partNumber: 'C40H32D400' },
            { type: 'paired', tripPartNumber: 'C4035E400', basePartNumber: 'C40H3' },
            { type: 'paired', tripPartNumber: 'C4036E400', basePartNumber: 'C40H3' },
            { type: 'single', partNumber: 'C63H32D630' },
            { type: 'paired', tripPartNumber: 'C6335E630', basePartNumber: 'C63H3' },
            { type: 'paired', tripPartNumber: 'C6336E630', basePartNumber: 'C63H3' },
            { type: 'single', partNumber: '33461' },
            { type: 'single', partNumber: '33547' },
            { type: 'single', partNumber: '34421' },
            { type: 'single', partNumber: '33467' },
            { type: 'single', partNumber: '33238' },
            { type: 'single', partNumber: '33553' },
            { type: 'single', partNumber: '33338' },
            { type: 'single', partNumber: '34425' },
            { type: 'single', partNumber: '33473' },
            { type: 'single', partNumber: '33248' },
            { type: 'single', partNumber: '33559' },
            { type: 'single', partNumber: '33348' },
            { type: 'single', partNumber: '34429' },
            { type: 'single', partNumber: '33479' },
            { type: 'single', partNumber: '33258' },
            { type: 'single', partNumber: '33565' },
            { type: 'single', partNumber: '33358' },
            { type: 'single', partNumber: '34433' },
            { type: 'single', partNumber: '33483' },
            { type: 'single', partNumber: '33268' },
            { type: 'single', partNumber: '33569' },
            { type: 'single', partNumber: '33368' },
            { type: 'single', partNumber: '34437' }
        ]
    },
    {
        heading: "Circuit Breaker Accessories",
        rows: [
            { type: 'single', partNumber: 'LV429517' },
            { type: 'single', partNumber: 'LV432593' },
            { type: 'single', partNumber: '33628' },
            { type: 'single', partNumber: 'LV429338T' },
            { type: 'single', partNumber: 'LV432598T' },
            { type: 'single', partNumber: '33873' },
            { type: 'single', partNumber: 'LV429489' },
            { type: 'single', partNumber: 'LV429493' },
            { type: 'single', partNumber: 'LV432465' },
            { type: 'single', partNumber: '29450' },
            { type: 'single', partNumber: 'LV429387' },
            { type: 'single', partNumber: 'LV429434' },
            { type: 'single', partNumber: 'LV431541' },
            { type: 'single', partNumber: 'LV432641' },
            { type: 'single', partNumber: 'NS1600MO' },
            { type: 'single', partNumber: '41950' },
            { type: 'single', partNumber: '41950' },
            { type: 'single', partNumber: 'LV431569' },
            { type: 'single', partNumber: 'LV432861' }
        ]
    },
    {
        heading: "CNSX Chassis – 50kA – 440A",
        rows: [
            { type: 'single', partNumber: 'CNSXA09SSRHTF' },
            { type: 'single', partNumber: 'CNSXA12SSRHTF' },
            { type: 'single', partNumber: 'CNSXA15SSRHTF' },
            { type: 'single', partNumber: 'CNSXA18SSRHTF' },
            { type: 'single', partNumber: 'CNSXA12DS' },
            { type: 'single', partNumber: 'CNSXA18DS' },
            { type: 'single', partNumber: 'CNSXA24DS' },
            { type: 'single', partNumber: 'CNSXA30DS' },
            { type: 'single', partNumber: 'CNSXA36DS' },
            { type: 'single', partNumber: 'CNSXA42DS' },
            { type: 'single', partNumber: 'CNSXA48DS' }
        ]
    },
    {
        heading: "CNSX Chassis – 50kA – 630A",
        rows: [
            { type: 'single', partNumber: 'CNSXB09SSRHTF' },
            { type: 'single', partNumber: 'CNSXB12SSRHTF' },
            { type: 'single', partNumber: 'CNSXB15SSRHTF' },
            { type: 'single', partNumber: 'CNSXB18SSRHTF' },
            { type: 'single', partNumber: 'CNSXB24SSRHTF' },
            { type: 'single', partNumber: 'CNSXB30SSRHTF' },
            { type: 'single', partNumber: 'CNSXB12DS' },
            { type: 'single', partNumber: 'CNSXB18DS' },
            { type: 'single', partNumber: 'CNSXB24DS' },
            { type: 'single', partNumber: 'CNSXB30DS' },
            { type: 'single', partNumber: 'CNSXB36DS' },
            { type: 'single', partNumber: 'CNSXB42DS' },
            { type: 'single', partNumber: 'CNSXB48DS' },
            { type: 'single', partNumber: 'CNSXB60DS' }
        ]
    },
    {
        heading: "Miniature Chassis",
        rows: [
            { type: 'sideBySide', partNumberA: 'SAU25012183', partNumberB: 'SAU40012183' },
            { type: 'sideBySide', partNumberA: 'SAU25018183', partNumberB: 'SAU40018183' },
            { type: 'sideBySide', partNumberA: 'SAU25024183', partNumberB: 'SAU40024183' },
            { type: 'sideBySide', partNumberA: 'SAU25036183', partNumberB: 'SAU40036183' },
            { type: 'sideBySide', partNumberA: 'SAU25048183', partNumberB: 'SAU40048183' },
            { type: 'sideBySide', partNumberA: 'SAU25060183', partNumberB: 'SAU40060183' },
            { type: 'sideBySide', partNumberA: 'SAU25072183', partNumberB: 'SAU40072183' },
            { type: 'sideBySide', partNumberA: 'SAU25084183', partNumberB: 'SAU40084183' },
            { type: 'sideBySide', partNumberA: 'SAU25096183', partNumberB: 'SAU40096183' },
            { type: 'sideBySide', partNumberA: 'SAU250108183', partNumberB: 'SAU400108183' }
        ]
    },
    {
        heading: "Neutral and Earth Links – 165A",
        rows: [
            { type: 'single', partNumber: 'enb12' },
            { type: 'single', partNumber: 'enb18' },
            { type: 'single', partNumber: 'enb24' },
            { type: 'single', partNumber: 'enb36' },
            { type: 'single', partNumber: 'enb48' },
            { type: 'single', partNumber: 'enb60' },
            { type: 'single', partNumber: 'enb72' },
            { type: 'single', partNumber: 'enb84' },
            { type: 'single', partNumber: 'enb96' },
            { type: 'single', partNumber: 'enb108' }
        ]
    },
    {
        heading: "Miniature Chassis Components",
        rows: [
            { type: 'single', partNumber: 'A9F44163' },
            { type: 'single', partNumber: 'A9F44363' },
            { type: 'single', partNumber: 'A9D61845' },
            { type: 'single', partNumber: 'A9F54163' },
            { type: 'single', partNumber: 'A9F54363' },
            { type: 'single', partNumber: 'A9D11845' },
            { type: 'single', partNumber: 'A9V02763' },
            { type: 'single', partNumber: 'A9N18356' },
            { type: 'single', partNumber: 'A9N18357' },
            { type: 'single', partNumber: 'A9N18358' },
            { type: 'single', partNumber: 'A9N18359' },
            { type: 'single', partNumber: 'A9N18364' },
            { type: 'single', partNumber: 'A9N18365' },
            { type: 'single', partNumber: 'A9N18367' },
            { type: 'single', partNumber: 'A9N18369' },
            { type: 'single', partNumber: 'A9S66191' },
            { type: 'single', partNumber: 'A9S66391' },
            { type: 'single', partNumber: 'A9A26380' },
            { type: 'single', partNumber: '26975' },
            { type: 'single', partNumber: 'A9XPH124' },
            { type: 'single', partNumber: 'A9XPH324' },
            { type: 'single', partNumber: 'A9A26975' }
        ]
    },
    {
        heading: "ATS 3P/4P",
        rows: [
            { type: 'single', partNumber: 'BLV429632/29642' },
            { type: 'single', partNumber: 'BLV429630/29640' },
            { type: 'single', partNumber: 'BLV430631/30641' },
            { type: 'single', partNumber: 'BLV431631/31641' },
            { type: 'single', partNumber: 'BLV431630/31640' },
            { type: 'single', partNumber: 'BLV432693/32694' },
            { type: 'single', partNumber: 'BLV432695/32696' },
            { type: 'single', partNumber: 'NS800N ML2.0 3P/4P BTS' },
            { type: 'single', partNumber: 'NS1000N ML2.0 3P/4P BTS' },
            { type: 'single', partNumber: 'NS1250N ML2.0 3P/4P BTS' },
            { type: 'single', partNumber: 'NS1600N ML2.0 3P/4P BTS' },
            { type: 'single', partNumber: 'SCH_ATS_LOGIC' },
            { type: 'single', partNumber: '29472' },
            { type: 'single', partNumber: 'RM17TG00' },
            { type: 'single', partNumber: 'LV429358' },
            { type: 'single', partNumber: 'LV432620' }
        ]
    },
    {
        heading: "Air Circuit Breakers – 3P with OCR",
        rows: [
            { type: 'single', partNumber: 'MTZ2-12H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-16H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-20H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-25H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-32H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-40H1D3PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-12H1D4PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-16H1D4PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-20H1D4PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-25H1D4PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-32H1D4PML2.0X' },
            { type: 'single', partNumber: 'MTZ2-40H1D4PML2.0X' }
        ]
    },
    {
        heading: "Air Circuit Breakers – Accessory",
        rows: [
            { type: 'single', partNumber: 'NS1600N_ML5-ML2' },
            { type: 'single', partNumber: 'MTZ ACB MOTOR MECH' },
            { type: 'single', partNumber: 'MTZ_ACB_MECH_INTERLOCK' },
            { type: 'single', partNumber: 'MTZ_ACB_LOGIC' }
        ]
    }
];
